# Generated by Django 3.2.18 on 2023-02-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StreetCard_FHIR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('client_id', models.CharField(max_length=120)),
                ('scope', models.CharField(max_length=120)),
                ('url', models.URLField()),
                ('redirect_uri', models.URLField()),
                ('patientId', models.CharField(max_length=100)),
                ('patientName', models.CharField(max_length=100)),
            ],
        ),
    ]
