# Generated by Django 4.1.7 on 2023-02-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetcard_fhir', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streetcard_fhir',
            name='redirect_uri',
            field=models.CharField(max_length=200),
        ),
    ]
