# Generated by Django 3.2.18 on 2023-03-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetcard_fhir', '0004_provider_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FhirEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='fhir_endpoints',
            field=models.ManyToManyField(to='streetcard_fhir.FhirEndpoint'),
        ),
    ]
