# Generated by Django 3.2.18 on 2023-03-17 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetcard_fhir', '0006_auto_20230316_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fhirendpoint',
            name='scope',
            field=models.CharField(max_length=1000),
        ),
    ]
