# Generated by Django 3.2.18 on 2023-03-17 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streetcard_fhir', '0006_auto_20230316_1736'),
        ('streetcard_fhir', '0007_alter_fhirendpoint_scope'),
    ]

    operations = [
    ]
