# Generated by Django 4.2 on 2023-04-11 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streetcard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='agencies',
            field=models.ManyToManyField(blank=True, related_name='agency_clients', to='streetcard.agency'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='providers',
            field=models.ManyToManyField(blank=True, to='streetcard.provider'),
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='provider',
            name='clients',
            field=models.ManyToManyField(blank=True, to='streetcard.client'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='company_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='provider',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
