# Generated by Django 4.2 on 2023-04-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetcard', '0002_client_provider_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('client', 'Client'), ('provider', 'Provider')], default='Client', max_length=10),
            preserve_default=False,
        ),
    ]
