# Generated by Django 4.2 on 2023-04-12 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetcard', '0002_alter_client_agencies_alter_client_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FhirEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('client_id', models.CharField(max_length=120)),
                ('redirect_uri', models.CharField(max_length=200)),
                ('scope', models.CharField(max_length=1000)),
                ('agencies', models.ManyToManyField(blank=True, to='streetcard.agency')),
            ],
        ),
        migrations.AddField(
            model_name='agency',
            name='endpoints',
            field=models.ManyToManyField(blank=True, to='streetcard.fhirendpoint'),
        ),
    ]
