# Generated by Django 4.2 on 2023-04-14 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetcard', '0003_fhirendpoint_agency_endpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cerner_sandbox_patientId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
