# Generated by Django 4.2 on 2023-04-16 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streetcard', '0004_client_cerner_sandbox_patientid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='company_name',
        ),
    ]
